url: "http://eracom-id471.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

navigation:
  - title: Jeux
    url: /videogames.html
  - title: Bande-dessinée
    url: /bd.html
  - title: Movies
    url: /movies.html
  - title: Séries
    url: /serie.html
